package xyz.lawlietbot.spring.syncserver;

public enum EventOut {

    FORWARD,
    COMMAND_LIST,
    FAQ_LIST,
    SERVER_STATS,
    TOPGG,
    TOPGG_ANICORD,
    FR_FETCH,
    FR_BOOST,
    FR_CAN_POST,
    FR_POST,
    INVITE,
    PREMIUM,
    PREMIUM_MODIFY,
    REPORT,
    STRIPE,
    PADDLE,
    DASH_INIT,
    DASH_CAT_INIT,
    DASH_ACTION,
    DASH_LIST_DISCORD_ENTITIES,
    DASH_COUNT_DISCORD_ENTITIES,
    PADDLE_SUBS,
    USER_CHECK_BANNED,
    DEV_VOTES_INIT,
    DEV_VOTES_UPDATE_REMINDER,
    DEV_VOTES_UPDATE_VOTES

}
